#ifndef CODE_CPP_CODE_CPP_BASE_IO_SSTREAM_SSTREAM_ENTRY_H_
#define CODE_CPP_CODE_CPP_BASE_IO_SSTREAM_SSTREAM_ENTRY_H_

class SstreamEntry {
 public:
  static void SstreamProgram();
};

#endif //CODE_CPP_CODE_CPP_BASE_IO_SSTREAM_SSTREAM_ENTRY_H_
