//
// Created by 85339 on 2022/10/13.
//

#ifndef CODE_CPP_CODE_CPP_BASE_STRING_STRING_ENTRY_H_
#define CODE_CPP_CODE_CPP_BASE_STRING_STRING_ENTRY_H_

class StringEntry {

};

#endif //CODE_CPP_CODE_CPP_BASE_STRING_STRING_ENTRY_H_
