#ifndef CODE_CPP_CODE_CPP_BASE_IO_ISTREAM_ISTREAM_ENTRY_H_
#define CODE_CPP_CODE_CPP_BASE_IO_ISTREAM_ISTREAM_ENTRY_H_

class IstreamEntry {
 public:
  static void IstreamProgram();
};

#endif //CODE_CPP_CODE_CPP_BASE_IO_ISTREAM_ISTREAM_ENTRY_H_
