#ifndef CODE_CPP_CODE_CPP_BASE_IO_OSTREAM_OSTREAM_ENTRY_H_
#define CODE_CPP_CODE_CPP_BASE_IO_OSTREAM_OSTREAM_ENTRY_H_

class OstreamEntry {
 public:
  static void OstreamProgram();
};

#endif //CODE_CPP_CODE_CPP_BASE_IO_OSTREAM_OSTREAM_ENTRY_H_
